# If port selection via ttys.py is enabled by `MOST_RECENT_PORT=1`, filter
# USB serials to only select the UART bridge of integrated J-Link debugger.
TTY_BOARD_FILTER := --model J-Link

# The TTY serial also is the ID of the debug adapter, as the TTY is provided by
# the debug adapter
DEBUG_ADAPTER_ID_IS_TTY_SERIAL := 1

JLINK_PRE_FLASH = ?

JLINK_POST_FLASH = Write4 0x10001200 00000012 00000012

include $(RIOTBOARD)/common/nrf52xxxdk/Makefile.include
